# Generated by Django 4.1 on 2023-06-01 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodotti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProdottoCarrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantità', models.PositiveIntegerField()),
                ('carrello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodotti.carrello')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodotti.prodotto')),
            ],
        ),
        migrations.AddField(
            model_name='carrello',
            name='prodotti',
            field=models.ManyToManyField(through='prodotti.ProdottoCarrello', to='prodotti.prodotto'),
        ),
        migrations.AddField(
            model_name='carrello',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
