# Generated by Django 4.1 on 2023-06-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0002_carrello_prodottocarrello_carrello_prodotti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodottocarrello',
            name='carrello',
        ),
        migrations.RemoveField(
            model_name='prodottocarrello',
            name='prodotto',
        ),
        migrations.DeleteModel(
            name='Carrello',
        ),
        migrations.DeleteModel(
            name='ProdottoCarrello',
        ),
    ]
