# Generated by Django 4.1 on 2023-06-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0003_remove_prodottocarrello_carrello_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
